name: Tests

on: [push, pull_request]

jobs:
  unit_tests:
    name: unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: Install meson
        run: |
          sudo apt-get install -y meson

      - name: Install plenary
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ../plenary.nvim

      - name: Run tests
        run: |
          nvim --version
          make test
